
services:
  open-hivemind-agent:
    image: mhand79/open-hivemind:latest
    restart: unless-stopped
    ports:
      - "3001:3001"  # Adjust the port mapping as per your application's requirement
    environment:
      - NODE_ENV=development # Needed for multi-stage ie installs compiler `tsc`
    env_file:
      - .env
    volumes:
      - ./config:/config
    logging:
      driver: json-file
      options:
        max-size: "100k"
        max-file: "3"
        mode: non-blocking
